name: Deploy to gh-pages

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy_with_NEBULA:
    permissions: 
      contents: write
    uses: esciencecenter-digital-skills/NEBULA/.github/workflows/deploy.yml@v1.0.0
    with:
      content_organization: ${{ github.repository_owner}}
      content_repository: ${{ github.event.repository.name }}
      content_ref: ${{ github.sha }}
      nebula_ref: v1.0.0
      deploy_to_ghpages: true
